language: ruby
cache: bundler
sudo: false

rvm:
  - 2.1.1
  - ruby-head

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - daniel.blancorojas@gmail.com
    on_failure: change
    on_success: never

